/*
 Navicat Premium Dump SQL

 Source Server         : MySql
 Source Server Type    : MySQL
 Source Server Version : 80042 (8.0.42)
 Source Host           : localhost:3306
 Source Schema         : wk_mails

 Target Server Type    : MySQL
 Target Server Version : 80042 (8.0.42)
 File Encoding         : 65001

 Date: 11/07/2025 11:33:17
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ee_mails
-- ----------------------------
DROP TABLE IF EXISTS `ee_mails`;
CREATE TABLE `ee_mails`  (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '邮件表',
  `from` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '发送人',
  `to` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '接收人',
  `subject` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '邮件主题',
  `text` text CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL COMMENT '发送内容',
  `template` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT NULL COMMENT '模板位置',
  `data` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT NULL COMMENT '模板数据',
  `cc` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT NULL COMMENT '抄送',
  `bcc` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT NULL COMMENT '密送',
  `status` varchar(5) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '发送状态',
  `error` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NULL DEFAULT NULL COMMENT '错误信息',
  `created_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 40 CHARACTER SET = utf8mb3 COLLATE = utf8mb3_unicode_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of ee_mails
-- ----------------------------
INSERT INTO `ee_mails` VALUES (32, '2270851619@qq.com', '3179174149@qq.com', '验证码', '<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>邮件验证码</title>\n</head>\n<body>\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\n    <tbody><tr>\n        <td>\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\n                <tbody><tr style=\"height: 30px;width: 100%;\">\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\n                    </td>\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\n                </tr>\n                <tr style=\"width:100%;\">\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\n                </tr>\n                </tbody></table>\n            <table>\n                <tbody>\n                <tr>\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\n                        您的邮箱验证码为：\n                    </td>\n                </tr>\n                <tr>\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\n                        <code style=\"display: block;text-align: center;\">2,850</code>\n                    </td>\n                </tr>\n                <tr>\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\n                    </td>\n                </tr>\n                </tbody>\n            </table>\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\n                <tbody style=\"width: 100%;\">\n                <tr style=\"width:100%;\">\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\n                </tr>\n                <tr style=\"width: 100%;\">\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\n                </tr>\n                <tr>\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\n                </tr>\n                </tbody>\n            </table>\n        </td>\n    </tr>\n    </tbody></table>\n    </div>\n</body>\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-03 16:44:02');
INSERT INTO `ee_mails` VALUES (33, '2270851619@qq.com', '3179174149@qq.com', '验证码', '<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>邮件验证码</title>\n</head>\n<body>\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\n    <tbody><tr>\n        <td>\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\n                <tbody><tr style=\"height: 30px;width: 100%;\">\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\n                    </td>\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\n                </tr>\n                <tr style=\"width:100%;\">\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\n                </tr>\n                </tbody></table>\n            <table>\n                <tbody>\n                <tr>\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\n                        您的邮箱验证码为：\n                    </td>\n                </tr>\n                <tr>\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\n                        <code style=\"display: block;text-align: center;\">6,600</code>\n                    </td>\n                </tr>\n                <tr>\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\n                    </td>\n                </tr>\n                </tbody>\n            </table>\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\n                <tbody style=\"width: 100%;\">\n                <tr style=\"width:100%;\">\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\n                </tr>\n                <tr style=\"width: 100%;\">\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\n                </tr>\n                <tr>\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\n                </tr>\n                </tbody>\n            </table>\n        </td>\n    </tr>\n    </tbody></table>\n    </div>\n</body>\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-03 16:46:33');
INSERT INTO `ee_mails` VALUES (34, '2270851619@qq.com', '1520163083@qq.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">8,048</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-05 17:35:27');
INSERT INTO `ee_mails` VALUES (35, '2270851619@qq.com', '2039452789@qq.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">4,464</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-10 22:05:00');
INSERT INTO `ee_mails` VALUES (36, '2270851619@qq.com', '2039452789@qq.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">9,940</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-10 22:06:24');
INSERT INTO `ee_mails` VALUES (37, '2270851619@qq.com', '1955161832@qq.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">7,147</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-10 22:10:11');
INSERT INTO `ee_mails` VALUES (38, '2270851619@qq.com', '3096143705@qq.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">6,963</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-10 22:11:01');
INSERT INTO `ee_mails` VALUES (39, '2270851619@qq.com', 'weizhihang2026@163.com', '验证码', '<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n    <meta charset=\"UTF-8\">\r\n    <title>邮件验证码</title>\r\n</head>\r\n<body>\r\n<table style=\"margin:0px;padding-left: 20px;padding-right: 20px;max-width: 700px;margin: auto;width: 100%;\">\r\n    <tbody><tr>\r\n        <td>\r\n            <table style=\"max-width: 700px; width: 100%;margin-top: 5px;\">\r\n                <tbody><tr style=\"height: 30px;width: 100%;\">\r\n                    <td style=\"width: 50%;vertical-align:bottom;\" valign=\"bottom\">\r\n                        <h1 style=\"font-size: 18px;margin: 0\">为考-考试系统</h1>\r\n                    </td>\r\n                    <td style=\"width: 50%;vertical-align:bottom;color:#76808E;font-size:12px;\" align=\"right\" valign=\"bottom\">让学习更高效</td>\r\n                </tr>\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"width: 100%;border-bottom-color: #ccc;border-bottom-width: 1px; border-bottom-style: solid;height: 15px;\"></td>\r\n                </tr>\r\n                </tbody></table>\r\n            <table>\r\n                <tbody>\r\n                <tr>\r\n                    <td style=\"padding-top: 30px;font-size: 20px;color: #323A45;\">\r\n                        您的邮箱验证码为：\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td valign=\"left\" style=\"font-size: 36px;color: #323A45;height: 110px;\">\r\n                        <code style=\"display: block;text-align: center;\">5,725</code>\r\n                    </td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 14px;  padding: 10px 0;\">\r\n                        该验证码 10 分钟内有效。为了保障您的账户安全，请勿向他人泄漏验证码信息。\r\n                    </td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n            <table style=\"max-width: 700px; width:100%; font-size:14px; text-align: center;padding-top:20px;color:#76808E;\">\r\n                <tbody style=\"width: 100%;\">\r\n                <tr style=\"width:100%;\">\r\n                    <td colspan=\"2\" style=\"height: 15px;width:100%;border-top-color: #ccc;  border-top-width: 1px;  border-top-style: solid;\"></td>\r\n                </tr>\r\n                <tr style=\"width: 100%;\">\r\n                    <td>如您对 为考 的使用有任何疑问, 请随时与我们联系。</td>\r\n                </tr>\r\n                <tr>\r\n                    <td style=\"font-size: 12px;\">Copyright © 2021 Baymax 版权所有</td>\r\n                </tr>\r\n                </tbody>\r\n            </table>\r\n        </td>\r\n    </tr>\r\n    </tbody></table>\r\n    </div>\r\n</body>\r\n</html>', 'EmailCode.html', NULL, NULL, NULL, 'ok', NULL, '2025-07-11 10:36:46');

SET FOREIGN_KEY_CHECKS = 1;
